In [4]:
# import packages and the file
import pandas as pd
import numpy as np
file = r"C:\Users\adishree.b\Downloads\Post-Campaign-audience-report-Ran_20191011_113007_609299279_2683686262.xlsx"
try:
    df = pd.read_excel(file)
except IOError:
    print('Error: can\'t find the file, please check if the path and/or filename is correct')
else:
    print("File loaded successfully")

File loaded successfully

In [8]:
df.head()

,Audience List,Impressions,Clicks,Click Rate (CTR),Complete Views (Video),TrueView: Views
0,(Deleted) Semasio » UK: Interest » Family & Pa...,4,0,0,3.0,0.0
1,19_Ford_Shopper_EcoSport_Competitors_Polk_InMa...,19,0,0,16.0,0.0
2,19_Ford_Shopper_F150_Competitors_Polk_InMarket...,27,0,0,21.0,0.0
3,33Across AudienceID » Arts » Digital » Graphics,467,0,0,293.0,0.0
4,33Across AudienceID » Arts » Entertainment,566,0,0,356.0,0.0

In [9]:
df.isnull().sum()

Audience List             0
Impressions               0
Clicks                    0
Click Rate (CTR)          0
Complete Views (Video)    0
TrueView: Views           0
dtype: int64

In [16]:
df["Audience List"].head(5)

0    (Deleted) Semasio » UK: Interest » Family & Pa...
1    19_Ford_Shopper_EcoSport_Competitors_Polk_InMa...
2    19_Ford_Shopper_F150_Competitors_Polk_InMarket...
3      33Across AudienceID » Arts » Digital » Graphics
4           33Across AudienceID » Arts » Entertainment
Name: Audience List, dtype: object

In [14]:
# drop na values
df.dropna(inplace = True)
# Split the first column "Audience List" by the deliminator " » "
dfa = df["Audience List"].str.split(pat=" » ", n = 4, expand=True)
# Add the columns to the new dataframe 'dfa' from the previous dataframe "df"
dfa["Impressions"] = df["Impressions"]
dfa["Clicks"] = df["Clicks"]
dfa["Complete_Views_Video"] = df["Complete Views (Video)"]
dfa["Audience List Type"] = df['Audience List']

In [20]:
dfa = df["Audience List"].str.split(pat=" » ", n = 4, expand=True)

In [21]:
dfa

                                                        0
0       (Deleted) Semasio » UK: Interest » Family & Pa...
1       19_Ford_Shopper_EcoSport_Competitors_Polk_InMa...
2       19_Ford_Shopper_F150_Competitors_Polk_InMarket...
3         33Across AudienceID » Arts » Digital » Graphics
4              33Across AudienceID » Arts » Entertainment
5                      33Across AudienceID » Arts » Music
6              33Across AudienceID » Auto » American Auto
7                33Across AudienceID » Auto » Luxury Auto
8       33Across AudienceID » Consumer Information » A...
9       33Across AudienceID » Financial Services » Ban...
10                33Across AudienceID » Food » Home Cooks
11      33Across AudienceID » Health » Alternative Med...
12      33Across AudienceID » Health » Nutrition » Senior
13           33Across AudienceID » Health » Womens_Health
14         33Across AudienceID » Hobbies » Coupon Clipper
15      33Across AudienceID » Hobbies » Outdoor Enthus...
16          33Across AudienceID » Home » Apartment_Living
17       33Across AudienceID » Home » Cooking » Chocolate
18      33Across AudienceID » Home » Cooking » Vegetarian
19      33Across AudienceID » Home » Do_It_Yourself » ...
20      33Across AudienceID » Home » Home_Improvement ...
21      33Across AudienceID » Home » Home_Improvement ...
22      33Across AudienceID » Home » Home_Improvement ...
23      33Across AudienceID » Personal Care » Healthy ...
24      33Across AudienceID » Personal Care » Women's ...
25       33Across AudienceID » Seasonal » Tax Preparation
26       33Across AudienceID » Shopping » Retail Shoppers
27                   33Across AudienceID » Small Business
28      33Across AudienceID » Small Business » Busines...
29                           33Across AudienceID » Sports
...                                                   ...
166697            zeotap » Brazil » Interest » Technology
166698    zeotap » Canada » App Usage » Events » Weddings
166699  zeotap » Canada » App Usage » Holidays » Chris...
166700  zeotap » France » Interest » Business » Busine...
166701       zeotap » Germany » Demographics » Age: 18-34
166702  zeotap » Germany » Interest » Communication » ...
166703  zeotap » Germany » Interest » Fashion & Beauty...
166704  zeotap » Germany » Interest » Health & Fitness...
166705  zeotap » Germany » Purchase Intent » Fashion &...
166706  zeotap » Germany » Purchase Intent » Fashion &...
166707  zeotap » Germany » Purchase Intent » Holidays ...
166708  zeotap » Germany » Purchase Intent » Shopping ...
166709  zeotap » Germany » Purchase Intent » Technolog...
166710  zeotap » India » Demographic » Audience Discovery
166711      zeotap » Mexico » Interest » Fashion & Beauty
166712               zeotap » Mexico » Interest » Science
166713  zeotap » Mexico » Interest » Shopping » Online...
166714    zeotap » Mexico » Interest » Shopping » Tickets
166715               zeotap » Mexico » Interest » Society
166716            zeotap » Mexico » Interest » Technology
166717  zeotap » Mexico » Interest » Technology & Comp...
166718  zeotap » Mexico » Interest » Videos, TV & Cine...
166719  zeotap » UK » App Usage » Automotive » Navigation
166720      zeotap » UK » Interest » Arts & Entertainment
166721  zeotap » UK » Purchase Intent » Business » Off...
166722  zeotap » UK » Standard » Purchase Intent » Fas...
166723  zeotap » UK » Standard » Purchase Intent » Hob...
166724  zeotap » UK » Standard » Purchase Intent » Hom...
166725  zeotap » UK » Standard » Purchase Intent » Travel
166726  zeotap » US » App Usage » Arts & Entertainment...

[166727 rows x 1 columns]

In [17]:
dfa.columns

Index([0, u'Impressions', u'Clicks', u'Complete_Views_Video',
       u'Audience List Type'],
      dtype='object')

In [13]:
# Rename the column names
dfa.columns = ['Audience source', 'Categories', 'T1', 'T2', 4, 'Impressions', 'Clicks', 'Complete_Views_Video', 'Audience List Type']
# Remove the column no 4 which is not required
dfa.drop([4], axis = 1, inplace = True)
# Filter the Audience source for 'Display & Video 360 Audiences' and the Categories for 'Affinity Categories' and 'In-Market Categories'

dff = dfa[dfa['Audience List Type'] == 'Bid Manager Audiences']

# Change the datatype of metrics to integer
dff['Impressions'] = dff['Impressions'].astype(int)
dff['Clicks'] = dff['Clicks'].astype(int)
dff['Complete_Views_Video'] = dff['Complete_Views_Video'].astype(int)
# Filter out the rows with Impressions less than 1000
greateror1000 =  dff['Impressions'] > 999
dff = dff[greateror1000]

# Remove the null T2 value
dff.dropna(inplace = True)
# Create CTR and VCR Columns

dff['CTR'] = dff["Clicks"]/dff['Impressions']
dff['VCR'] = dff["Complete_Views_Video"]/dff['Impressions']

ValueError: Length mismatch: Expected axis has 5 elements, new values have 9 elements

In [ ]:
# Save the output in a csv file
dff.to_csv(r"C:\\Users\\adishree.b\\Documents\\Files\\post campaign analysis and audience\\out3.csv", index = False)